---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: clusters-service-read-entitlements
    namespace: flux-system
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: clusters-service-secrets-role
subjects:
    - kind: ServiceAccount
      name: {{ include "mccp.serviceAccountName" . }}
      namespace: {{ .Release.Namespace | quote }}
---
{{- if .Values.config.capi.clusters.namespace }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: clusters-service-secrets-role
    namespace: {{ .Values.config.capi.clusters.namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: clusters-service-secrets-role
subjects:
    - kind: ServiceAccount
      name: {{ include "mccp.serviceAccountName" . }}
      namespace: {{ .Release.Namespace | quote }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: clusters-service-secrets-role
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: clusters-service-secrets-role
subjects:
    - kind: ServiceAccount
      name: {{ include "mccp.serviceAccountName" . }}
      namespace: {{ .Release.Namespace | quote }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: clusters-service-secrets-role-default
    namespace: {{ .Release.Namespace | quote }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: clusters-service-secrets-role
subjects:
    - kind: ServiceAccount
      name: {{ include "mccp.serviceAccountName" . }}
      namespace: {{ .Release.Namespace | quote }}