{{- if .Values.explorer.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.explorer.collector.serviceAccount.name | quote }}
  namespace: {{ .Values.explorer.collector.serviceAccount.namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.explorer.collector.serviceAccount.name | quote }}
rules:
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles", "clusterroles", "rolebindings", "clusterrolebindings" ]
    verbs: [ "list", "watch" ]
  - apiGroups: [ "kustomize.toolkit.fluxcd.io" ]
    resources: [ "kustomizations" ]
    verbs: [ "list", "watch" ]
  - apiGroups: [ "helm.toolkit.fluxcd.io" ]
    resources: [ "helmreleases" ]
    verbs: [ "list", "watch" ]
  - apiGroups: [ "source.toolkit.fluxcd.io" ]
    resources: [ "buckets", "helmcharts", "gitrepositories", "helmrepositories", "ocirepositories" ]
    verbs: [ "list", "watch" ]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["templates.weave.works"]
    resources: ["gitopssets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["capi.weave.works"]
    resources: ["capitemplates"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["templates.weave.works"]
    resources: ["gitopstemplates"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.explorer.collector.serviceAccount.name | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.explorer.collector.serviceAccount.name | quote }}
    namespace: {{ .Values.explorer.collector.serviceAccount.namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.explorer.collector.serviceAccount.name | quote }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
