apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusters-service-gitopscluster-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitopscluster-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "mccp.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
