apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "templates-controller.fullname" . }}-manager-role
  labels:
  {{- include "templates-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - capi.weave.works
  resources:
  - capitemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capi.weave.works
  resources:
  - capitemplates/finalizers
  verbs:
  - update
- apiGroups:
  - capi.weave.works
  resources:
  - capitemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - templates.weave.works
  resources:
  - gitopstemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.weave.works
  resources:
  - gitopstemplates/finalizers
  verbs:
  - update
- apiGroups:
  - templates.weave.works
  resources:
  - gitopstemplates/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "templates-controller.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: templates-controller
    app.kubernetes.io/part-of: templates-controller
  {{- include "templates-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "templates-controller.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "templates-controller.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'