apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "templates-controller.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "templates-controller.fullname" . }}-serving-cert
  labels:
  {{- include "templates-controller.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "templates-controller.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-capi-weave-works-v1alpha1-capitemplate
  failurePolicy: Fail
  name: capitemplates.weave.works
  rules:
  - apiGroups:
    - capi.weave.works
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - capitemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "templates-controller.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-templates-weave-works-v1alpha1-gitopstemplate
  failurePolicy: Fail
  name: templates.weave.works
  rules:
  - apiGroups:
    - templates.weave.works
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gitopstemplates
  sideEffects: None