apiVersion: v1
kind: Service
metadata:
  name: {{ include "templates-controller.fullname" . }}-webhook-service
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: templates-controller
    app.kubernetes.io/part-of: templates-controller
  {{- include "templates-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    control-plane: controller-manager
  {{- include "templates-controller.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 -}}