apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: podinfo-dev-github
  namespace: flux-system
spec:
  type: generic
  address: http://chart-pipeline-controller-promotion.flux-system.svc.cluster.local:8082/promotion/flux-system/podinfo-github/dev
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: podinfo-dev-github
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
  - kind: HelmRelease
    name: podinfo
    namespace: dev-github
  exclusionList:
  - .*upgrade.*has.*started
  - .*is.*not.*ready
  - ^Dependencies.*
  providerRef:
    name: podinfo-dev-github
