version: 2
updates:
  # Maintain dependencies for frontend
  - package-ecosystem: "npm"
    directory: "/ui-cra"
    schedule:
      interval: "daily"
    reviewers:
      - "weaveworks/timber-wolf"
      - "weaveworks/pesto"
      - "weaveworks/wild-watermelon"
      - "weaveworks/tangerine"

  # Maintain dependencies for backend
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "weaveworks/timber-wolf"
      - "weaveworks/pesto"
      - "weaveworks/wild-watermelon"
      - "weaveworks/tangerine"