project_name: gitops-ee
release:
  disable: true
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
archives:
  - format: tar.gz
    name_template: >-
      gitops-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
builds:
  - <<: &build_defaults
      binary: "gitops"
      main: ./cmd/gitops
      ldflags:
        - "{{ .Env.LDFLAGS }}"
      env:
        - CGO_ENABLED=0
    id: linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    goarm:
      - 7
blobs:
  - provider: s3
    bucket: weave-gitops-enterprise
    folder: "releases/bin/{{.Version}}"
    region: "us-east-1"
