project_name: gitops
release:
  disable: true
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
archives:
  - format: tar.gz
    replacements:
      amd64: x86_64
    name_template: "gitops-{{.Os}}-{{.Arch}}"
builds:
  - <<: &build_defaults
      binary: "gitops"
      main: ./cmd/gitops
      ldflags:
        - "{{ .Env.LDFLAGS }}"
      env:
        - CGO_ENABLED=0
    id: linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    goarm:
      - 7
  - <<: *build_defaults
    id: linux-arm64
    goos:
      - linux
    goarch:
      - arm64
    goarm:
      - 7
  - <<: *build_defaults
    id: linux-arm
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
  - <<: *build_defaults
    id: darwin-amd64
    goos:
      - darwin
    goarch:
      - amd64
  - <<: *build_defaults
    id: darwin-arm64
    goos:
      - darwin
    goarch:
      - arm64
brews:
  - name: gitops-ee
    tap:
      owner: weaveworks
      name: homebrew-tap
    commit_author:
      name: weave-gitops-bot
      email: weave-gitops-bot@weave.works
    folder: Formula
    url_template: "https://artifacts.wge.dev.weave.works/releases/bin/{{ .Version }}/gitops-{{.Os}}-{{.Arch}}"
    homepage: "https://docs.gitops.weave.works/docs/getting-started"
    description: "GitOps support for Kubernetes"
    custom_require: "./lib/wge_auth_download_strategy"
    download_strategy: WGEAuthDownloadStrategy
    install: |
      bin.install "gitops"
      # Install bash completion
      output = Utils.popen_read("#{bin}/gitops completion bash")
      (bash_completion/"gitops").write output

      # Install zsh completion
      output = Utils.popen_read("#{bin}/gitops completion zsh")
      (zsh_completion/"_gitops").write output
blobs:
  - provider: s3
    bucket: weave-gitops-enterprise
    folder: "releases/bin/{{.Version}}"
    region: "us-east-1"
