{{- if .Values.rbac.adminUserRoleBindings.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wego-admin-read-apps
  namespace: flux-system
subjects:
- kind: User
  name: "wego-admin"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: gitops-apps-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wego-admin-read-templates
  namespace: {{ .Values.config.capi.templates.namespace }}
subjects:
- kind: User
  name: "wego-admin"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: gitops-templates-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wego-admin-read-cluster-secrets
  namespace: {{ .Values.config.capi.clusters.namespace }}
subjects:
- kind: User
  name: "wego-admin"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: gitops-secrets-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wego-admin-read-release-namespace-secrets
  namespace: {{ .Release.Namespace | quote }}
subjects:
- kind: User
  name: "wego-admin"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: gitops-secrets-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wego-admin-read-identities
subjects:
- kind: User
  name: "wego-admin"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: gitops-identities-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wego-admin-read-policies
subjects:
- kind: User
  name: "wego-admin"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: gitops-policies-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wego-admin-read-gitopsclusters
  namespace: {{ .Values.config.capi.clusters.namespace }}
subjects:
- kind: User
  name: "wego-admin"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: gitops-gitopsclusters-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}