# permissions for end users to view Kubeconfig secrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusters-service-secrets-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    # create to create deploy key secrets
    # read to read capi secrets like kubeconfig
    verbs: ["create", "get", "watch", "list"]
