name: 'Setup SSH'
description: 'Setup SSH keys and known hosts'
inputs:
  ssh-private-key:
    description: 'ssh keys to load'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up ssh agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
    - name: Add known_hosts
      shell: bash
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keygen -R github.com
        ssh-keygen -R gitlab.com
        ssh-keygen -R gitlab.git.dev.weave.works
        
        # Append fresh new keys
        ssh-keyscan github.com gitlab.com gitlab.git.dev.weave.works >> ~/.ssh/known_hosts
