apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pipeline-controller.fullname" . }}-editor
  labels:
  {{- include "pipeline-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - pipelines.weave.works
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipelines.weave.works
  resources:
  - pipelines/status
  verbs:
  - get