apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pipeline-controller.fullname" . }}-leader-election
  labels:
  {{- include "pipeline-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pipeline-controller.fullname" . }}-leader-election
  labels:
  {{- include "pipeline-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "pipeline-controller.fullname" . }}-leader-election'
subjects:
- kind: ServiceAccount
  name: '{{ include "pipeline-controller.fullname" . }}'
  namespace: '{{ .Release.Namespace }}'