apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-controller.fullname" . }}-controller-manager
  labels:
  {{- include "cluster-controller.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-controller.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "cluster-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "cluster-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        azure-extensions-usage-release-identifier: {{ .Release.Name }}
        control-plane: controller-manager
      {{- include "cluster-controller.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.global.azure.images.kubeRbacProxy.registry }}/{{ .Values.global.azure.images.kubeRbacProxy.image }}@{{ .Values.global.azure.images.kubeRbacProxy.digest }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: {{- toYaml .Values.controllerManager.kubeRbacProxy.resources | nindent
          10 }}
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        - --capi-enabled={{ .Values.global.capiEnabled }}
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.global.azure.images.clusterController.registry }}/{{ .Values.global.azure.images.clusterController.image }}@{{ .Values.global.azure.images.clusterController.digest }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "cluster-controller.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10