# permissions for end users to view capitemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capitemplate-viewer-role
rules:
  - apiGroups:
      - capi.weave.works
    resources:
      - capitemplates
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - capi.weave.works
    resources:
      - capitemplates/status
    verbs:
      - get
