apiVersion: v1
kind: Secret
metadata:
  name: cluster-user-auth
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  username: d2Vnby1hZG1pbg==
  password: {{ .Values.config.auth.userAccount.password | quote | bcrypt | b64enc }}