apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusters-service-customresourcedefinitions-reader
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    # read used to detect if flagger is installed
    verbs: ["get", "list", "watch"]
