// Generated by dts-bundle-generator v5.9.0
//
// ...and then hand editted by weaveworks employees
//

/// <reference types="hoist-non-react-statics" />
/// <reference types="node" />
/// <reference types="prop-types" />
/// <reference types="react" />
/// <reference types="scheduler" />
/// <reference types="styled-components" />

declare module '@weaveworks/weave-gitops' {
  export type Condition = {
    type?: string;
    status?: string;
    reason?: string;
    message?: string;
    timestamp?: number;
  };
  export type Application = {
    name?: string;
    path?: string;
    url?: string;
    sourceConditions?: Condition[];
    deploymentConditions?: Condition[];
  };
  export declare function AppContextProvider({
    applicationsClient,
    ...props
  }: Props): JSX.Element;
  // export declare const theme: import("styled-components").DefaultTheme;
  // export declare const AppContextProvider: typeof _AppContextProvider;
  export declare const Applications: import('styled-components').StyledComponent<
    ({ className }: { className?: string }) => JSX.Element,
    import('styled-components').DefaultTheme,
    {},
    never
  >;
  export declare const ApplicationDetail: import('styled-components').StyledComponent<
    ({ className }: { className?: string }) => JSX.Element,
    import('styled-components').DefaultTheme,
    {},
    never
  >;
  export declare const applicationsClient: typeof appsClient;
}
