// Code generated by counterfeiter. DO NOT EDIT.
package storefakes

import (
	"sync"

	"github.com/weaveworks/weave-gitops-enterprise/pkg/query/internal/models"
	"github.com/weaveworks/weave-gitops-enterprise/pkg/query/store"
)

type FakeStoreWriter struct {
	GetAccessRulesStub        func() ([]models.AccessRule, error)
	getAccessRulesMutex       sync.RWMutex
	getAccessRulesArgsForCall []struct {
	}
	getAccessRulesReturns struct {
		result1 []models.AccessRule
		result2 error
	}
	getAccessRulesReturnsOnCall map[int]struct {
		result1 []models.AccessRule
		result2 error
	}
	GetObjectsStub        func() ([]models.Object, error)
	getObjectsMutex       sync.RWMutex
	getObjectsArgsForCall []struct {
	}
	getObjectsReturns struct {
		result1 []models.Object
		result2 error
	}
	getObjectsReturnsOnCall map[int]struct {
		result1 []models.Object
		result2 error
	}
	StoreAccessRulesStub        func([]models.AccessRule) error
	storeAccessRulesMutex       sync.RWMutex
	storeAccessRulesArgsForCall []struct {
		arg1 []models.AccessRule
	}
	storeAccessRulesReturns struct {
		result1 error
	}
	storeAccessRulesReturnsOnCall map[int]struct {
		result1 error
	}
	StoreObjectsStub        func([]models.Object) error
	storeObjectsMutex       sync.RWMutex
	storeObjectsArgsForCall []struct {
		arg1 []models.Object
	}
	storeObjectsReturns struct {
		result1 error
	}
	storeObjectsReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStoreWriter) GetAccessRules() ([]models.AccessRule, error) {
	fake.getAccessRulesMutex.Lock()
	ret, specificReturn := fake.getAccessRulesReturnsOnCall[len(fake.getAccessRulesArgsForCall)]
	fake.getAccessRulesArgsForCall = append(fake.getAccessRulesArgsForCall, struct {
	}{})
	stub := fake.GetAccessRulesStub
	fakeReturns := fake.getAccessRulesReturns
	fake.recordInvocation("GetAccessRules", []interface{}{})
	fake.getAccessRulesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStoreWriter) GetAccessRulesCallCount() int {
	fake.getAccessRulesMutex.RLock()
	defer fake.getAccessRulesMutex.RUnlock()
	return len(fake.getAccessRulesArgsForCall)
}

func (fake *FakeStoreWriter) GetAccessRulesCalls(stub func() ([]models.AccessRule, error)) {
	fake.getAccessRulesMutex.Lock()
	defer fake.getAccessRulesMutex.Unlock()
	fake.GetAccessRulesStub = stub
}

func (fake *FakeStoreWriter) GetAccessRulesReturns(result1 []models.AccessRule, result2 error) {
	fake.getAccessRulesMutex.Lock()
	defer fake.getAccessRulesMutex.Unlock()
	fake.GetAccessRulesStub = nil
	fake.getAccessRulesReturns = struct {
		result1 []models.AccessRule
		result2 error
	}{result1, result2}
}

func (fake *FakeStoreWriter) GetAccessRulesReturnsOnCall(i int, result1 []models.AccessRule, result2 error) {
	fake.getAccessRulesMutex.Lock()
	defer fake.getAccessRulesMutex.Unlock()
	fake.GetAccessRulesStub = nil
	if fake.getAccessRulesReturnsOnCall == nil {
		fake.getAccessRulesReturnsOnCall = make(map[int]struct {
			result1 []models.AccessRule
			result2 error
		})
	}
	fake.getAccessRulesReturnsOnCall[i] = struct {
		result1 []models.AccessRule
		result2 error
	}{result1, result2}
}

func (fake *FakeStoreWriter) GetObjects() ([]models.Object, error) {
	fake.getObjectsMutex.Lock()
	ret, specificReturn := fake.getObjectsReturnsOnCall[len(fake.getObjectsArgsForCall)]
	fake.getObjectsArgsForCall = append(fake.getObjectsArgsForCall, struct {
	}{})
	stub := fake.GetObjectsStub
	fakeReturns := fake.getObjectsReturns
	fake.recordInvocation("GetObjects", []interface{}{})
	fake.getObjectsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStoreWriter) GetObjectsCallCount() int {
	fake.getObjectsMutex.RLock()
	defer fake.getObjectsMutex.RUnlock()
	return len(fake.getObjectsArgsForCall)
}

func (fake *FakeStoreWriter) GetObjectsCalls(stub func() ([]models.Object, error)) {
	fake.getObjectsMutex.Lock()
	defer fake.getObjectsMutex.Unlock()
	fake.GetObjectsStub = stub
}

func (fake *FakeStoreWriter) GetObjectsReturns(result1 []models.Object, result2 error) {
	fake.getObjectsMutex.Lock()
	defer fake.getObjectsMutex.Unlock()
	fake.GetObjectsStub = nil
	fake.getObjectsReturns = struct {
		result1 []models.Object
		result2 error
	}{result1, result2}
}

func (fake *FakeStoreWriter) GetObjectsReturnsOnCall(i int, result1 []models.Object, result2 error) {
	fake.getObjectsMutex.Lock()
	defer fake.getObjectsMutex.Unlock()
	fake.GetObjectsStub = nil
	if fake.getObjectsReturnsOnCall == nil {
		fake.getObjectsReturnsOnCall = make(map[int]struct {
			result1 []models.Object
			result2 error
		})
	}
	fake.getObjectsReturnsOnCall[i] = struct {
		result1 []models.Object
		result2 error
	}{result1, result2}
}

func (fake *FakeStoreWriter) StoreAccessRules(arg1 []models.AccessRule) error {
	var arg1Copy []models.AccessRule
	if arg1 != nil {
		arg1Copy = make([]models.AccessRule, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.storeAccessRulesMutex.Lock()
	ret, specificReturn := fake.storeAccessRulesReturnsOnCall[len(fake.storeAccessRulesArgsForCall)]
	fake.storeAccessRulesArgsForCall = append(fake.storeAccessRulesArgsForCall, struct {
		arg1 []models.AccessRule
	}{arg1Copy})
	stub := fake.StoreAccessRulesStub
	fakeReturns := fake.storeAccessRulesReturns
	fake.recordInvocation("StoreAccessRules", []interface{}{arg1Copy})
	fake.storeAccessRulesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStoreWriter) StoreAccessRulesCallCount() int {
	fake.storeAccessRulesMutex.RLock()
	defer fake.storeAccessRulesMutex.RUnlock()
	return len(fake.storeAccessRulesArgsForCall)
}

func (fake *FakeStoreWriter) StoreAccessRulesCalls(stub func([]models.AccessRule) error) {
	fake.storeAccessRulesMutex.Lock()
	defer fake.storeAccessRulesMutex.Unlock()
	fake.StoreAccessRulesStub = stub
}

func (fake *FakeStoreWriter) StoreAccessRulesArgsForCall(i int) []models.AccessRule {
	fake.storeAccessRulesMutex.RLock()
	defer fake.storeAccessRulesMutex.RUnlock()
	argsForCall := fake.storeAccessRulesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStoreWriter) StoreAccessRulesReturns(result1 error) {
	fake.storeAccessRulesMutex.Lock()
	defer fake.storeAccessRulesMutex.Unlock()
	fake.StoreAccessRulesStub = nil
	fake.storeAccessRulesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStoreWriter) StoreAccessRulesReturnsOnCall(i int, result1 error) {
	fake.storeAccessRulesMutex.Lock()
	defer fake.storeAccessRulesMutex.Unlock()
	fake.StoreAccessRulesStub = nil
	if fake.storeAccessRulesReturnsOnCall == nil {
		fake.storeAccessRulesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.storeAccessRulesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStoreWriter) StoreObjects(arg1 []models.Object) error {
	var arg1Copy []models.Object
	if arg1 != nil {
		arg1Copy = make([]models.Object, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.storeObjectsMutex.Lock()
	ret, specificReturn := fake.storeObjectsReturnsOnCall[len(fake.storeObjectsArgsForCall)]
	fake.storeObjectsArgsForCall = append(fake.storeObjectsArgsForCall, struct {
		arg1 []models.Object
	}{arg1Copy})
	stub := fake.StoreObjectsStub
	fakeReturns := fake.storeObjectsReturns
	fake.recordInvocation("StoreObjects", []interface{}{arg1Copy})
	fake.storeObjectsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStoreWriter) StoreObjectsCallCount() int {
	fake.storeObjectsMutex.RLock()
	defer fake.storeObjectsMutex.RUnlock()
	return len(fake.storeObjectsArgsForCall)
}

func (fake *FakeStoreWriter) StoreObjectsCalls(stub func([]models.Object) error) {
	fake.storeObjectsMutex.Lock()
	defer fake.storeObjectsMutex.Unlock()
	fake.StoreObjectsStub = stub
}

func (fake *FakeStoreWriter) StoreObjectsArgsForCall(i int) []models.Object {
	fake.storeObjectsMutex.RLock()
	defer fake.storeObjectsMutex.RUnlock()
	argsForCall := fake.storeObjectsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStoreWriter) StoreObjectsReturns(result1 error) {
	fake.storeObjectsMutex.Lock()
	defer fake.storeObjectsMutex.Unlock()
	fake.StoreObjectsStub = nil
	fake.storeObjectsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStoreWriter) StoreObjectsReturnsOnCall(i int, result1 error) {
	fake.storeObjectsMutex.Lock()
	defer fake.storeObjectsMutex.Unlock()
	fake.StoreObjectsStub = nil
	if fake.storeObjectsReturnsOnCall == nil {
		fake.storeObjectsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.storeObjectsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStoreWriter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getAccessRulesMutex.RLock()
	defer fake.getAccessRulesMutex.RUnlock()
	fake.getObjectsMutex.RLock()
	defer fake.getObjectsMutex.RUnlock()
	fake.storeAccessRulesMutex.RLock()
	defer fake.storeAccessRulesMutex.RUnlock()
	fake.storeObjectsMutex.RLock()
	defer fake.storeObjectsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStoreWriter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ store.StoreWriter = new(FakeStoreWriter)
