name: "Get gitops binary"
description: "Get or build the gitops binary"
inputs:
  path:
    description: "where shall it go?"
    required: true
    default: /tmp/gitops
  ref:
    description: "want a special git commit?"
    required: false
    default: ""
  runs-on:
    description: "`macOS-latest` or `ubuntu-latest`"
    required: false
    default: "ubuntu-latest"
  os-name:
    description: "`linux` or `darwin`"
    required: false
    default: "linux"
runs:
  using: "composite"
  steps:
    - name: Download gitops binary from s3
      shell: bash
      if: ${{ inputs.ref == '' }}
      run: |
        wget https://weave-gitops.s3.us-east-2.amazonaws.com/gitops-${{ inputs.runs-on }}        
        mv gitops-${{ inputs.runs-on }} ${{ inputs.path }}
        sudo chmod +x ${{ inputs.path }}

        # curl -LO https://github.com/weaveworks/weave-gitops/releases/download/v0.5.0-rc2/gitops-${{ inputs.os-name }}-x86_64.tar.gz
        # tar -xf gitops-${{ inputs.os-name }}-x86_64.tar.gz
        # mv gitops ${{ inputs.path }}

        # Print out Version
        ${{ inputs.path }} version
    - uses: actions/checkout@v3
      if: ${{ inputs.ref != '' }}
      with:
        repository: weaveworks/weave-gitops
        path: /tmp/weave-gitops
        ref: ${{ inputs.ref }}
    - name: "build from source"
      shell: bash
      if: ${{ inputs.ref != '' }}
      run: |
        cd /tmp/weave-gitops
        make gitops
        mv bin/gitops ${{ inputs.path }}
