# This dockerfile builds an alpine container with sqlite installed
# that can be used to query the mccp sqlite database.
# To inspect the database exec into the container with the attached
# persistent volume claim and run:
# $ sqlite3

FROM alpine:3.12

RUN apk add --no-cache tini sqlite

ENTRYPOINT [ "/sbin/tini" ]
