apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: prod-github
spec:
  interval: 1m
  chart:
    spec:
      chart: podinfo
      version: "6.0.0" # {"$promotion": "flux-system:podinfo-github:prod"}
      sourceRef:
        kind: HelmRepository
        name: podinfo
      interval: 1m
