apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusters-service-impersonator-role
rules:
  - apiGroups: [""]
    resources: ["users", "groups"]
    verbs: ["impersonate"]
{{- if .Values.explorer.enabled }}
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts" ]
    verbs: [ "impersonate" ]
    resourceNames:
      - {{ .Values.explorer.collector.serviceAccount.name | quote }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusters-service-impersonator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusters-service-impersonator-role
subjects:
  - kind: ServiceAccount
    name: {{ include "mccp.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
