apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: weaveworks-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://raw.githubusercontent.com/weaveworks/weave-gitops-profile-examples/gh-pages
