apiVersion: clustertemplates.weave.works/v1alpha1
kind: GitOpsTemplate
metadata:
  name: sample-wge-tf-controller-template
  namespace: default
spec:
  description: This is a sample WGE template that will be translated into a tf-controller specific template.
  params:
    - name: CLUSTER_NAME
      description: Name of the cluster.
    - name: RESOURCE_NAME
      description: Name of the template.
    - name: NAMESPACE
      description: Namespace to create the Terraform resource in.
    - name: GIT_REPO_NAMESPACE
      description: Namespace of the configuring git repository object.
    - name: GIT_REPO_NAME
      description: Name of the configuring git repository.
    - name: TEMPLATE_PATH
      # tf-controller is an important distinction because we aren't generating terraform templates we
      # are generating Terraform Kind out of these.
      description: Path to the generated tf-controller templates.
  resourcetemplates:
    - apiVersion: tfcontroller.contrib.fluxcd.io/v1alpha1
      kind: Terraform
      metadata:
        name: ${RESOURCE_NAME}
        namespace: ${NAMESPACE}
      spec:
        interval: 1h
        path: ${TEMPLATE_PATH}
        approvePlan: "auto"
        vars:
          - name: cluster_identifier
            value: ${CLUSTER_NAME}
        sourceRef:
          kind: GitRepository
          name: ${GIT_REPO_NAME}
          namespace: ${GIT_REPO_NAMESPACE}
