apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  name: gitopsset-configmaps
  namespace: default
spec:
  generators:
    - list:
        elements:
          - env: dev
            team: dev-team
          - env: production
            team: ops-team
          - env: staging
            team: ops-team
  templates:
    - content:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: "{{ .Element.env }}-info-configmap"
          namespace: default
        spec:
          data:
            team: "{{ .Element.team }}"
            env: "{{ .Element.env }}"
            description: "This is a configmap for the {{ .Element.env }} environment"
