apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: weave-gitops-quickstart
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: add-monitoring
  url: https://github.com/weaveworks/weave-gitops-quickstart
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-config
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: weave-gitops-quickstart-monitoring
  path: ./monitoring
  prune: true
