name: "Get a gitops binary"

on:
  workflow_call:
    inputs:
      ref:
        description: "which binary to get"
        default: "main"
        required: false
        type: string

jobs:
  latest-main:
    if: inputs.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Download gitops binary from s3
        shell: bash
        run: |
          wget https://weave-gitops.s3.us-east-2.amazonaws.com/gitops-${{ inputs.runs-on }}        
          mv gitops-${{ inputs.runs-on }} gitops

          # curl -LO https://github.com/weaveworks/weave-gitops/releases/download/v0.5.0-rc2/gitops-${{ inputs.os-name }}-x86_64.tar.gz
          # tar -xf gitops-${{ inputs.os-name }}-x86_64.tar.gz
          # mv gitops ${{ inputs.path }}
      - uses: actions/upload-artifact@v2
        with:
          name: gitops
          path: gitops
          retention-days: 1

  build-a-commit:
    if: inputs.ref != 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/checkout@v2
        with:
          repository: weaveworks/weave-gitops
          token: ${{ github.token }}
          ref: ${{ inputs.ref }}
      - name: Clean
        run: make clean
      - name: build
        run: |
          make gitops
      - uses: actions/upload-artifact@v2
        with:
          name: gitops
          path: bin/gitops
          retention-days: 1
