on: 
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
name: label
jobs:
  labelCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Pull request label check
        uses: NathanielHill/check-pr-label-action@v4.0.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'bug, enhancement, ui, test, null'