apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-controller.fullname" . }}-manager-role
  labels:
  {{- include "cluster-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gitops.weave.works
  resources:
  - gitopsclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitops.weave.works
  resources:
  - gitopsclusters/finalizers
  verbs:
  - update
- apiGroups:
  - gitops.weave.works
  resources:
  - gitopsclusters/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-controller.fullname" . }}-manager-rolebinding
  labels:
  {{- include "cluster-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "cluster-controller.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "cluster-controller.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'